### PR TITLE
Css canvas medical - Damien Martinez

### PR DESCRIPTION
**Pull request by damien-martinez**
STILL IN PROGRESS

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Damien! Just submitting a review so that I know this is still in progress and not ready for review.

**Comment by damien-martinez** [comment]
Completed screenshot
Screen Shot 2022-02-05 at 3 53 11 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Damien! I see that you have a `container` and a `row` class, but you have no `column` classes at all. I suggest you review `css-layout-classes`, then please revise this to make proper use of `column` classes.

**Comment by damien-martinez** [comment]
> Hey Damien! I see that you have a `container` and a `row` class, but you have no `column` classes at all. I suggest you review `css-layout-classes`, then please revise this to make proper use of `column` classes.

Hi, I have added the columns I needed.

Thank you for the feedback.
Screen Shot 2022-02-07 at 9 09 09 PM

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
